FROM python:3.7-alpine

COPY requirements.txt /app/
RUN apk update && apk add musl-dev gcc && pip install -r /app/requirements.txt

COPY languages/ /app/languages
COPY src/ /app/src

CMD ["python", "/app/src/main.py"]
